services:
  db:
    container_name: peeng_db
    image: postgres:14.20
    restart: always
    volumes:
      - peeng_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: peeng_db
    ports:
      - 5432:5432

  messaging:
    container_name: peeng_queue
    image: rabbitmq:4.1.4-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  peeng_volume:
