spring:
  application:
    name: peeng
  config:
    import: file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/peeng_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

app:
  security:
    jwt: ${JWT_SECRET}
