package com.dawood.peeng.common.enums;

public enum ErrorCode {
  USER_NOT_FOUND,
  INVALID_CREDENTIALS,
  TENANT_NOT_FOUND,
  MEMBERSHIP_NOT_FOUND,
  ACCESS_DENIED,
  VALIDATION_ERROR,
  BAD_REQUEST, INTERNAL_SERVER_ERROR, RESOURCE_ALREADY_EXISTS
}
